// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesToDo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Game", b =>
                {
                    b.Property<Guid>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GameCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("GameRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RemainingHoursToBeat")
                        .HasColumnType("int");

                    b.Property<int>("TotalHoursToBeat")
                        .HasColumnType("int");

                    b.HasKey("GameID");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            GameID = new Guid("08b59be3-592a-4704-86f5-99fb6a8959d5"),
                            GameCompleted = false,
                            GameRating = "M",
                            GameTitle = "Hayes and Sons",
                            RemainingHoursToBeat = 66,
                            TotalHoursToBeat = 2
                        },
                        new
                        {
                            GameID = new Guid("4b6bc82e-fcd4-4342-92da-d86536c58bc1"),
                            GameCompleted = false,
                            GameRating = "M",
                            GameTitle = "Upton-Roberts",
                            RemainingHoursToBeat = 79,
                            TotalHoursToBeat = 62
                        },
                        new
                        {
                            GameID = new Guid("51eb6f01-36e9-4667-a4bb-593e10144db5"),
                            GameCompleted = false,
                            GameRating = "M",
                            GameTitle = "Little, Walsh and Kuvalis",
                            RemainingHoursToBeat = 53,
                            TotalHoursToBeat = 80
                        },
                        new
                        {
                            GameID = new Guid("00746f8e-afbb-4c59-942e-e981fab339bc"),
                            GameCompleted = false,
                            GameRating = "M",
                            GameTitle = "Rath, Monahan and Hickle",
                            RemainingHoursToBeat = 65,
                            TotalHoursToBeat = 91
                        },
                        new
                        {
                            GameID = new Guid("f64b3a0d-2287-4daf-9f5b-4748f3b76985"),
                            GameCompleted = false,
                            GameRating = "M",
                            GameTitle = "Wisoky, Nikolaus and Nicolas",
                            RemainingHoursToBeat = 62,
                            TotalHoursToBeat = 83
                        },
                        new
                        {
                            GameID = new Guid("bc56fb1a-1825-48af-8bb3-5bf238084456"),
                            GameCompleted = false,
                            GameRating = "M",
                            GameTitle = "Erdman, Upton and Lynch",
                            RemainingHoursToBeat = 79,
                            TotalHoursToBeat = 24
                        },
                        new
                        {
                            GameID = new Guid("6a3b9dba-e9ff-47f0-83ad-76fe08fbed58"),
                            GameCompleted = true,
                            GameRating = "M",
                            GameTitle = "Schiller-Doyle",
                            RemainingHoursToBeat = 33,
                            TotalHoursToBeat = 99
                        },
                        new
                        {
                            GameID = new Guid("4c2ade8f-833b-4a23-be5f-76b0deeba4cd"),
                            GameCompleted = true,
                            GameRating = "M",
                            GameTitle = "Wisoky-Rippin",
                            RemainingHoursToBeat = 63,
                            TotalHoursToBeat = 77
                        },
                        new
                        {
                            GameID = new Guid("91d7fea5-3860-4f39-9f26-8e7f5fbfa8c9"),
                            GameCompleted = true,
                            GameRating = "M",
                            GameTitle = "Grady-Hilll",
                            RemainingHoursToBeat = 94,
                            TotalHoursToBeat = 85
                        },
                        new
                        {
                            GameID = new Guid("cc064a5b-66f1-4d64-bd20-4d815d5a77af"),
                            GameCompleted = true,
                            GameRating = "M",
                            GameTitle = "Satterfield and Sons",
                            RemainingHoursToBeat = 68,
                            TotalHoursToBeat = 62
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
